name: Publish PyPI

on:
  push:
    tags:
      - '@cloudflare/flagship-python@*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          working-directory: sdks/python

      - name: Build and publish to PyPI
        working-directory: sdks/python
        run: |
          uv build
          uv publish --token "$PYPI_TOKEN"
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
